export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";
export const GET_EVENTS_ACTION= "GET_EVENTS_ACTION";
export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_ACTION = "GET_CATEGORIES_ACTION";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_SUCCESS_NOTIFICATION = "CLEAR_SUCCESS_NOTIFICATION";
